# Node, Mongo, Redis, Nginx

version: "3.3"

services:
  api:
    image: node:latest
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./:/home/node/api/
    working_dir: /home/node/api
    command: npm start
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db/
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    image: redis:latest
    networks:
      - backend
    volumes:
      - redis:/data/redis/
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - api
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

networks:
  backend:

volumes:
  mongodb:
  redis: